# --- CONFIGURACIÓN DE SONARQUBE ---
sonar.projectKey=iconstruction
sonar.projectName=iConstruction
sonar.projectVersion=1.0

# --- RUTAS ---
sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8

# --- EXCLUSIONES ---
sonar.exclusions=**/migrations/**, **/__pycache__/**, **/venv/**, **/static/**, **/media/**

# --- TESTS Y COBERTURA ---
sonar.python.coverage.reportPaths=coverage.xml





