# Generated by Django 5.2.7 on 2025-10-21 06:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodeguero',
            fields=[
                ('id_bodeguero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_bodeguero', models.CharField(max_length=150)),
                ('apellido_bodeguero', models.CharField(max_length=150)),
                ('sueldo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('codigo_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaHerramienta',
            fields=[
                ('codigo_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaObra',
            fields=[
                ('codigo_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('codigo_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Especializacion',
            fields=[
                ('codigo_especializacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_especializacion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoHerramienta',
            fields=[
                ('codigo_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoObra',
            fields=[
                ('codigo_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaHerramienta',
            fields=[
                ('codigo_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaMaterial',
            fields=[
                ('codigo_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TipoBodega',
            fields=[
                ('codigo_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHerramienta',
            fields=[
                ('codigo_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('codigo_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('BODEGUERO', 'Bodeguero')], default='BODEGUERO', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('codigo_herramienta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_herramienta', models.CharField(max_length=200)),
                ('precio_herramienta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dimensiones', models.CharField(blank=True, max_length=200)),
                ('codigo_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas', to='appiconstruction.categoriaherramienta')),
                ('codigo_estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas', to='appiconstruction.estadoherramienta')),
                ('codigo_marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas', to='appiconstruction.marcaherramienta')),
                ('codigo_tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas', to='appiconstruction.tipoherramienta')),
            ],
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('VIEW', 'Visualización'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('PRESTAMO', 'Préstamo'), ('DEVOLUCION', 'Devolución')], max_length=20)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('objeto_id', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividad',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('codigo_material', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_material', models.CharField(max_length=200)),
                ('precio_material', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('codigo_marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='appiconstruction.marcamaterial')),
                ('codigo_tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='appiconstruction.tipomaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('codigo_obra', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_obra', models.CharField(max_length=200)),
                ('direccion_obra', models.CharField(blank=True, max_length=300)),
                ('metros_cuadrados', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('codigo_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='appiconstruction.categoriaobra')),
                ('codigo_comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='appiconstruction.comuna')),
                ('codigo_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='appiconstruction.estadoobra')),
            ],
        ),
        migrations.CreateModel(
            name='Obrero',
            fields=[
                ('id_obrero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_obrero', models.CharField(max_length=150)),
                ('apellido_obrero', models.CharField(max_length=150)),
                ('codigo_cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obreros', to='appiconstruction.cargo')),
                ('codigo_obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obreros', to='appiconstruction.obra')),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoHerramienta',
            fields=[
                ('codigo_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_devolucion_esperada', models.DateField(blank=True, null=True)),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('estado_al_prestar', models.CharField(blank=True, max_length=100)),
                ('estado_al_devolver', models.CharField(blank=True, max_length=100)),
                ('observaciones_prestamo', models.TextField(blank=True)),
                ('observaciones_devolucion', models.TextField(blank=True)),
                ('devuelto', models.BooleanField(default=False)),
                ('codigo_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='appiconstruction.herramienta')),
                ('id_obrero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_herramientas', to='appiconstruction.obrero')),
            ],
            options={
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='PrestamoMaterial',
            fields=[
                ('codigo_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_prestada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_prestamo', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_devolucion_esperada', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('devuelto', models.BooleanField(default=False)),
                ('codigo_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='appiconstruction.material')),
                ('id_obrero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_materiales', to='appiconstruction.obrero')),
            ],
            options={
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionMaterial',
            fields=[
                ('codigo_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_devuelta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_usada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('merma', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad que sobró pero no se puede reutilizar', max_digits=12)),
                ('fecha_devolucion', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
                ('codigo_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='appiconstruction.prestamomaterial')),
            ],
            options={
                'ordering': ['-fecha_devolucion'],
            },
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuario',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id_supervisor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_supervisor', models.CharField(max_length=150)),
                ('apellido_supervisor', models.CharField(max_length=150)),
                ('codigo_especializacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisores', to='appiconstruction.especializacion')),
                ('codigo_obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisores', to='appiconstruction.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('codigo_informe', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_informe', models.CharField(max_length=250)),
                ('fecha_informe', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('id_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes', to='appiconstruction.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('codigo_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_bodega', models.CharField(max_length=200)),
                ('direccion_bodega', models.CharField(blank=True, max_length=300)),
                ('capacidad', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('codigo_tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bodegas', to='appiconstruction.tipobodega')),
            ],
        ),
        migrations.CreateModel(
            name='BodegueroBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegueros', to='appiconstruction.bodega')),
                ('id_bodeguero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='appiconstruction.bodeguero')),
            ],
            options={
                'unique_together': {('codigo_bodega', 'id_bodeguero')},
            },
        ),
        migrations.CreateModel(
            name='HerramientaBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_almacenada', models.PositiveIntegerField(default=0)),
                ('codigo_bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herramientas', to='appiconstruction.bodega')),
                ('codigo_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='appiconstruction.herramienta')),
            ],
            options={
                'unique_together': {('codigo_herramienta', 'codigo_bodega')},
            },
        ),
        migrations.CreateModel(
            name='MaterialBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_almacenada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('codigo_bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='appiconstruction.bodega')),
                ('codigo_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='appiconstruction.material')),
            ],
            options={
                'unique_together': {('codigo_material', 'codigo_bodega')},
            },
        ),
        migrations.CreateModel(
            name='ObraMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_asignada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('codigo_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_asignadas', to='appiconstruction.material')),
                ('codigo_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_asignados', to='appiconstruction.obra')),
            ],
            options={
                'unique_together': {('codigo_obra', 'codigo_material')},
            },
        ),
        migrations.CreateModel(
            name='ObreroHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_uso', models.DateField(blank=True, null=True)),
                ('fecha_termino_uso', models.DateField(blank=True, null=True)),
                ('codigo_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obreros', to='appiconstruction.herramienta')),
                ('id_obrero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herramientas', to='appiconstruction.obrero')),
            ],
            options={
                'unique_together': {('id_obrero', 'codigo_herramienta')},
            },
        ),
    ]
