# Generated by Django 5.2.7 on 2025-10-21 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appiconstruction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='supervisor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_sistema', to='appiconstruction.supervisor'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('BODEGUERO', 'Bodeguero'), ('SUPERVISOR', 'Supervisor')], default='BODEGUERO', max_length=20),
        ),
    ]
