# Generated by Django 5.2.7 on 2025-10-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appiconstruction', '0002_usuario_supervisor_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='fecha_informe',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
