# Generated by Django 5.2.7 on 2025-10-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appiconstruction', '0003_alter_informe_fecha_informe'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='especificaciones',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='textura',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
