# Generated by Django 5.2.7 on 2025-10-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appiconstruction', '0004_herramienta_especificaciones_herramienta_textura'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='alto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='ancho',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='largo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
