# Generated by Django 5.2.7 on 2025-10-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appiconstruction', '0005_herramienta_alto_herramienta_ancho_herramienta_largo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramienta',
            name='dimensiones',
        ),
    ]
