# Generated by Django 5.2.7 on 2025-10-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appiconstruction', '0006_remove_herramienta_dimensiones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramienta',
            name='precio_herramienta',
        ),
        migrations.RemoveField(
            model_name='material',
            name='precio_material',
        ),
    ]
