# Generated by Django 5.2.7 on 2025-10-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appiconstruction', '0007_remove_herramienta_precio_herramienta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='material',
            name='condicion',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='material',
            name='presentacion',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='material',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
