# Generated by Django 5.2.7 on 2025-10-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appiconstruction', '0008_material_cantidad_material_color_material_condicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='acabado',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
