# Generated by Django 5.2.7 on 2025-10-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appiconstruction', '0009_material_acabado'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='alcance',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='alimentacion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='capacidad',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='diametro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='largo_cable',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='modelo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='potencia',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='rpm',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='ruedas',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='tamaño_mandril',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='voltaje',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
