# Generated by Django 5.2.7 on 2025-11-14 21:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appiconstruction', '0011_material_ancho_material_composicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='es_central',
            field=models.BooleanField(default=False, verbose_name='Es Bodega Central'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='region',
            field=models.CharField(blank=True, choices=[('ARICA', 'Arica y Parinacota'), ('TARAPACA', 'Tarapacá'), ('ANTOFAGASTA', 'Antofagasta'), ('ATACAMA', 'Atacama'), ('COQUIMBO', 'Coquimbo'), ('VALPARAISO', 'Valparaíso'), ('METROPOLITANA', 'Metropolitana'), ('OHIGGINS', "O'Higgins"), ('MAULE', 'Maule'), ('NUBLE', 'Ñuble'), ('BIOBIO', 'Biobío'), ('ARAUCANIA', 'Araucanía'), ('RIOS', 'Los Ríos'), ('LAGOS', 'Los Lagos'), ('AYSEN', 'Aysén'), ('MAGALLANES', 'Magallanes')], max_length=50),
        ),
        migrations.CreateModel(
            name='TransferenciaBodega',
            fields=[
                ('codigo_transferencia', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_transferencia', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='COMPLETADA', max_length=20)),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='appiconstruction.bodega')),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salida', to='appiconstruction.bodega')),
                ('codigo_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='appiconstruction.material')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia de Bodega',
                'verbose_name_plural': 'Transferencias de Bodega',
                'ordering': ['-fecha_transferencia'],
            },
        ),
    ]
