# Generated by Django 5.2.7 on 2025-11-14 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appiconstruction', '0012_bodega_es_central_bodega_region_transferenciabodega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodega',
            name='es_central',
        ),
        migrations.RemoveField(
            model_name='bodega',
            name='region',
        ),
        migrations.DeleteModel(
            name='TransferenciaBodega',
        ),
    ]
